spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/python
    username: python
    password: python
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: secret